POST http://localhost:3000/api/forgot-password
Content-Type: application/json

{
    "email": "phamvanhoang182004@gmail.com"
}

###
POST http://localhost:3000/api/verify-otp
Content-Type: application/json

{
    "email": "phamvanhoang182004@gmail.com",
    "otp": "186462"
}

###
POST http://localhost:3000/api/auth
Content-Type: application/json


{
    "email": "phamvanhoang182004@gmail.com",
    "password": "123456"
}
